spring.application.name=Ledger

# ===============================
# MySQL Configuration
# ===============================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/Ledger}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ===============================
# Server
# ===============================

server.port=${PORT:8080}